### ISSUE TITLE
Duplicate ID for Goalseeker Enchantment

### ISSUE THREAD

**Issue by Dcetidre** [ThexXTURBOXx/Reforged#139]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCoreMod (movingworld-MC1.8.9-INDEV-H-full.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 25/04/16 03:22 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.ExceptionInInitializerError
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ExceptionInInitializerError
    at org.silvercatcher.reforged.ReforgedRegistry.createItems(ReforgedRegistry.java:62)
    at org.silvercatcher.reforged.proxy.CommonProxy.preInit(CommonProxy.java:30)
    at org.silvercatcher.reforged.proxy.ClientProxy.preInit(ClientProxy.java:37)
    at org.silvercatcher.reforged.ReforgedMod.preInit(ReforgedMod.java:38)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
    ... 10 more
Caused by: java.lang.IllegalArgumentException: Duplicate enchantment id! class org.silvercatcher.reforged.enchantments.EnchantmentGoalseeker and class noppes.npcs.enchants.EnchantDamage Enchantment ID:100
    at net.minecraft.enchantment.Enchantment.<init>(Enchantment.java:64)
    at org.silvercatcher.reforged.enchantments.EnchantmentGoalseeker.<init>(EnchantmentGoalseeker.java:12)
    at org.silvercatcher.reforged.api.ReforgedAdditions.<clinit>(ReforgedAdditions.java:81)
    ... 40 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 7 (amd64) version 6.1
    CPU: 2x Intel(R) Celeron(R) CPU B800 @ 1.50GHz
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 211593920 bytes (201 MB) / 440545280 bytes (420 MB) up to 2120679424 bytes (2022 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1855 Optifine OptiFine_1.8.9_HD_U_H3 13 mods loaded, 13 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCH darkevilmac.movingworld.common.asm.coremod{} [MovingWorld CORE](minecraft.jar) 
    UCH FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1855.jar) 
    UCH Forge{11.15.1.1855} [Minecraft Forge](forge-1.8.9-11.15.1.1855.jar) 
    UCH MovingWorld{MC1.8.9-INDEV-H} [Moving World](movingworld-MC1.8.9-INDEV-H-full.jar) 
    UCH ArchimedesShipsPlus{MC1.8.9-INDEV-G} [Archimedes' Ships Plus](archimedesshipsplus-MC1.8.9-INDEV-G.jar) 
    UCH customnpcs{1.8.9_beta} [CustomNPCs](CustomNpcs_1.8.9_beta%2821feb16%29.jar) 
    UCE reforged{0.7-pre1} [Reforged](reforged-0.7-pre1-alpha-1.8.9.jar) 
    UCH worldedit{6.1.1} [WorldEdit](worldedit-forge-mc1.8.9-6.1.1.jar) 
    UCE ReforgedIntegrationCore{0.2.2-alpha} [Reforged|Integration Core](reforged-integration-0.2.2-alpha.jar) 
    UCE ReforgedProjectE{0.2.2-alpha} [Reforged|Integration ProjectE](reforged-integration-0.2.2-alpha.jar) 
    UCE ReforgedThaumcraft{0.2.2-alpha} [Reforged|Integration Thaumcraft](reforged-integration-0.2.2-alpha.jar) 
    UCH reforged_cag{1.0} [Reforged - Cross & Grave](reforged_cag-1.8.9-0.8.jar) 
    Loaded coremods (and transformers): 
MovingWorldCoreMod (movingworld-MC1.8.9-INDEV-H-full.jar)

```
GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics'
```

**Comment by TheOnlySilverClaw** [comment]
If you can, try to change the enchantment ID of CustomNPCs or Reforged (I'm currently not sure if we had an option for that, I'm a little out of touch with development right now).
We'll have to find a better way to handle enchantments in the long run.

**Comment by ThexXTURBOXx** [comment]
https://github.com/TheOnlySilverClaw/Reforged/commit/0a7f92c8f4b8119aac9384da38deb329c97ca412
Should I release a new version?
(The crossbow and the AReloadable-class still need to get fixed though...)

**Comment by TheOnlySilverClaw** [comment]
Yes, do that. I will try to get a look in the near future, but I'm pretty busy, at least until the 13th.

**Comment by ThexXTURBOXx** [comment]
Ok, I am pretty busy right now, too. I will release the new version tonight.

**Comment by ThexXTURBOXx** [comment]
Released new version.
