### ISSUE TITLE
Some reloadable weapons cause NullPointerException in multiserver

### ISSUE THREAD

**Issue by vias722** [ThexXTURBOXx/Reforged#152]
Reloadable Weapon(Musket and Blunderbuss) cause Exception when I try to reload them in multiserver.
This exception doesn't shut down my server.
Then, the reload looks finished correctly. But when I shoot it, no bullet fly from weapon.

I reproduce this exception in a server that includes no mod but Reforged.

This is Stacktrace:
 [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_102]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_102]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
        at org.silvercatcher.reforged.api.AReloadable.func_77659_a(AReloadable.java:91) ~[AReloadable.class:?]
        at org.silvercatcher.reforged.items.weapons.ItemMusket.func_77659_a(ItemMusket.java:29) ~[ItemMusket.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:152) ~[zx.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:335) ~[lg.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:578) ~[lm.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:59) ~[ja.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) ~[ja.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_102]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_102]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
        ... 5 more

**Comment by ThexXTURBOXx** [comment]
Ok, I could have thought of this error to occurr... This was just silly of me, I will fix it in the next update.
